// This file helps avoid circular dependencies
export type { Achievement } from './Achievement1';
export type { Event } from './Event';
export type { EventAttendee } from './EventAttendee';
export type { Inventory } from './Inventory';
export type { Item } from './Item';
export type { UserAchievement } from './UserAchievement';
export type { Survey } from './Survey';
export type { SurveyResponse } from './SurveyResponse';
export type { UserActivity } from './UserActivity';
export type { UserReward } from './UserReward';
export type { Wishlist } from './Wishlist';
export type { Minsite } from './Minsite';
export type { AffiliateLink } from './AffiliateLink';
export type { AffiliateProgram } from './AffiliateProgram';
export type { Grant } from './Grant';
export type { GroupMember } from './GroupMember';
export type { LinkedContent } from './LinkedContent';
export type { LinkPage } from './LinkPage';
export type { Notification } from './Notification';
export type { Petition } from './petition.model';
export type { Project } from './project.model';
export type { Resource } from './resource.model';
export type { Testimonial } from './Testimonial';
export type { Vote } from './vote.model';
export type { Link } from './Link';
export type { AIModel } from './AIModel';
export type { AIJob } from './AIJob';
export type { Theme } from './Theme';
export type { Playlist } from './Playlist';
export type { SupportTicket } from './SupportTicket';
export type { RecurringEvent } from './RecurringEvent';
export type { AvatarCustomization } from './AvatarCustomization';

// Import types from modules
export type { User } from '../modules/user/User';
export type { Campaign } from '../modules/campaign/Campaign';
export type { Reward } from '../modules/campaign/Reward';
export type { Contribution } from '../modules/campaign/Contribution';
