import { Express } from 'express';
import userRoutes from '../modules/user/userRoutes';
import companyRoutes from './companyRoutes';
import aiRoutes from '../modules/ai/aiRoutes';
import brandRoutes from './brandRoutes';
import affiliateProgramRoutes from '../modules/affiliate/affiliateProgramRoutes';
import affiliateLinkRoutes from '../modules/affiliate/affiliateLinkRoutes';
import affiliateRoutes from '../modules/affiliate/affiliateRoutes';
import clickTrackingRoutes from '../modules/dashboard/affiliate/clickTrackingRoutes';
import analyticsRoutes from '../modules/analytics/analyticsRoutes';
import linkInBioRoutes from './LinkInBioRoutes';
import recommendationRoutes from './recommendationRoutes';
import payoutRoutes from './payoutRoutes';
import minsiteRoutes from './minsiteRoutes';
import uploadRoutes from './uploadRoutes';
import testimonialRoutes from './testimonialRoutes';
import wishlistRoutes from './wishlistRoutes';
import communityWishlistRoutes from './communityWishlistRoutes';
import campaignRoutes from './campaignRoutes';
import groupRoutes from './groupRoutes';
import eventRoutes from './eventRoutes';
import n8nRoutes from './n8nRoutes';
import mauticRoutes from './mauticRoutes';
import gitRoutes from './gitRoutes';
import authRoutes from './authRoutes';
import aiEthicsRoutes from '../modules/ai/aiEthicsRoutes';

export const setupRoutes = (app: Express) => {
  app.use('/api/users', userRoutes);
  app.use('/api/companies', companyRoutes);
  app.use('/api/ai', aiRoutes);
  app.use('/api/brands', brandRoutes);
  app.use('/api/affiliate-programs', affiliateProgramRoutes);
  app.use('/api/affiliate-links', affiliateLinkRoutes);
  app.use('/api/affiliate', affiliateRoutes);
  app.use('/api/clicktracking', clickTrackingRoutes);
  app.use('/api/analytics', analyticsRoutes);
  app.use('/api/u', linkInBioRoutes);
  app.use('/api/recommendations', recommendationRoutes);
  app.use('/api/minsite', minsiteRoutes);
  app.use('/api/payouts', payoutRoutes);
  app.use('/api/upload', uploadRoutes);
  app.use('/api/testimonials', testimonialRoutes);
  app.use('/api/wishlist', wishlistRoutes);
  app.use('/api/community-wishlist', communityWishlistRoutes);
  app.use('/api/campaigns', campaignRoutes);
  app.use('/api/groups', groupRoutes);
  app.use('/api/events', eventRoutes);
  app.use('/api/n8n', n8nRoutes);
  app.use('/api/mautic', mauticRoutes);
  app.use('/api/git', gitRoutes);
  app.use('/api/auth', authRoutes);
  app.use('/api/ai-ethics', aiEthicsRoutes);
};
